#:schema node_modules/wrangler/config-schema.json
name = "bolt"
account_id = "1c21d1b951373276c7cffe10b4057a8e"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
pages_build_output_dir = "./build/client"
send_metrics = true

# R2 Storage configuration
[[r2_buckets]]
binding = "BOLT_STORAGE"
bucket_name = "bolt-storage"
preview_bucket_name = "bolt-storage-dev"

# D1 Database configuration
[[d1_databases]]
binding = "BOLT_DB"
database_name = "bolt-database"
database_id = "1c21d1b951373276c7cffe10b4057a8e" # Replace with actual DB ID after creation

# KV Namespace configuration
[[kv_namespaces]]
binding = "BOLT_CACHE"
id = "2fb4385d64154cf587396f6536d3cb77" # KV namespace ID
preview_id = "2fb4385d64154cf587396f6536d3cb77" # Using same ID for preview for now
