#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
pages_build_output_dir = "./build/client"
send_metrics = true

# R2 Storage configuration
[[r2_buckets]]
binding = "BOLT_STORAGE"
bucket_name = "bolt-storage"
preview_bucket_name = "bolt-storage-dev"

# D1 Database configuration
[[d1_databases]]
binding = "BOLT_DB"
database_name = "bolt-database"
database_id = "placeholder-db-id" # Replace with actual DB ID after creation

# KV Namespace configuration
[[kv_namespaces]]
binding = "BOLT_CACHE"
id = "placeholder-kv-id" # Replace with actual KV ID after creation
preview_id = "placeholder-preview-kv-id" # Replace with actual preview KV ID after creation
