#:schema node_modules/wrangler/config-schema.json
name = "bolt-diy"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-05-05"
pages_build_output_dir = "./build/client"
send_metrics = true
